import { test, expect } from '@playwright/test'

test('opponents exchange saved private messages without changing the chess position', async ({ browser, request }) => {
  test.setTimeout(60000)
  const a = await browser.newContext(), b = await browser.newContext()
  const white = await a.newPage(), black = await b.newPage()
  const suffix = Date.now()
  try {
    for (const [page, name] of [[white, `ChatA${suffix}`], [black, `ChatB${suffix}`]] as const) {
      await page.goto('http://127.0.0.1:5173/')
      await page.getByRole('button', { name: 'Online', exact: true }).click()
      await page.getByRole('button', { name: 'Create an account', exact: true }).click()
      await page.getByLabel('Player name').fill(name)
      await page.getByLabel('Email', { exact: true }).fill(`${name}@example.com`)
      await page.getByLabel('Password', { exact: true }).fill('Chess chat password 123')
      await page.getByRole('button', { name: 'Create account', exact: true }).click()
      await expect(page.getByText(`Playing as ${name}`, { exact: true })).toBeVisible()
    }
    const created = white.waitForResponse(response => response.url().endsWith('/api/games') && response.request().method() === 'POST')
    await white.getByRole('button', { name: 'Create online game', exact: true }).click()
    const { game } = await (await created).json()
    await expect(white.getByRole('button', { name: 'Send message', exact: true })).toBeDisabled()
    await black.locator('.online-row').filter({ hasText: `ChatA${suffix}` }).getByRole('button', { name: 'Join', exact: true }).click()
    await expect(white.getByLabel('Message your opponent')).toBeEnabled()
    const position = await (await a.request.get(`http://127.0.0.1:5173/api/games/${game.id}`)).json()
    await white.getByLabel('Message your opponent').fill('Hello! <b>Ready to play?</b>')
    await white.getByRole('button', { name: 'Send message', exact: true }).click()
    await expect(black.getByRole('log', { name: 'Chat messages', exact: true })).toContainText('Hello! <b>Ready to play?</b>')
    await black.getByRole('button', { name: 'Good luck!', exact: true }).click()
    await expect(white.getByRole('log', { name: 'Chat messages', exact: true })).toContainText('Good luck!')
    const after = await (await a.request.get(`http://127.0.0.1:5173/api/games/${game.id}`)).json()
    expect(after.game.version).toBe(position.game.version)
    expect(after.game.fen).toBe(position.game.fen)
    expect((await a.request.post(`http://127.0.0.1:5173/api/games/${game.id}/messages`, { data: { text: ' ' } })).status()).toBe(400)
    expect((await a.request.post(`http://127.0.0.1:5173/api/games/${game.id}/messages`, { data: { text: 'x'.repeat(501) } })).status()).toBe(400)
    await request.post('/api/auth/register', { data: { name: `Outsider${suffix}`, email: `outsider${suffix}@example.com`, password: 'Chess chat password 123' } })
    expect((await request.get(`/api/games/${game.id}/messages`)).status()).toBe(404)
    expect((await request.post(`/api/games/${game.id}/messages`, { data: { text: 'Intruder' } })).status()).toBe(404)
    await white.reload()
    await white.getByRole('button', { name: 'Online', exact: true }).click()
    await white.locator('.online-row').filter({ hasText: `ChatA${suffix}` }).getByRole('button', { name: 'Open', exact: true }).click()
    await expect(white.getByRole('log', { name: 'Chat messages', exact: true })).toContainText('Good luck!')
    await white.screenshot({ path: 'test-results/chat-desktop.png' })
  } finally { await a.close(); await b.close() }
})
