import { test, expect } from '@playwright/test'
import { Chess } from 'chess.js'
import { chooseMove, resultOf } from '../src/game'

test('same-device players can finish a game and restart', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Play a friend/ }).click()
  const square = (name: string) => page.getByRole('button', { name: new RegExp(`^${name} `) })
  await expect(page.getByRole('button', { name: /^[a-h][1-8] / })).toHaveCount(64)
  await square('f2').click()
  await square('f5').click()
  await expect(square('f2')).toHaveAttribute('aria-label', 'f2 White pawn')
  await square('f3').click()
  await square('e7').click(); await square('e5').click()
  await square('g2').click(); await square('g4').click()
  await square('d8').click(); await square('h4').click()
  await expect(page.getByRole('status')).toContainText('Black wins by checkmate')
  await square('e2').click(); await square('e4').click()
  await expect(square('e2')).toHaveAttribute('aria-label', 'e2 White pawn')
  await page.getByRole('button', { name: 'New game', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('White to move')
  await expect(square('d8')).toHaveAttribute('aria-label', 'd8 Black queen')
})

test('computer responds and the board fits a phone', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Play computer', exact: true }).click()
  await page.getByRole('button', { name: 'e2 White pawn' }).click()
  await page.getByRole('button', { name: /e4 empty/ }).click()
  await expect(page.getByRole('status')).toContainText('White to move', { timeout: 15000 })
  await expect(page.locator('.move-panel h3')).toContainText('2 moves')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Resign', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Black wins by resignation')
})

test('special rules and computer search preserve the position', () => {
  const castle = new Chess('r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1')
  castle.move('O-O')
  expect(castle.get('f1')?.type).toBe('r')
  const ep = new Chess()
  for (const move of ['e4', 'a6', 'e5', 'd5', 'exd6']) ep.move(move)
  expect(ep.get('d5')).toBeUndefined()
  expect(ep.get('d6')?.color).toBe('w')
  const promotion = new Chess('7k/P7/8/8/8/8/8/7K w - - 0 1')
  promotion.move({ from: 'a7', to: 'a8', promotion: 'n' })
  expect(promotion.get('a8')?.type).toBe('n')
  expect(resultOf(promotion)).toBe('Draw by insufficient material')
  expect(resultOf(new Chess('7k/5Q2/6K1/8/8/8/8/8 b - - 0 1'))).toBe('Draw by stalemate')
  const game = new Chess()
  for (const move of ['f3', 'e5', 'g4']) game.move(move)
  const before = game.fen()
  const choice = chooseMove(game)
  expect(game.fen()).toBe(before)
  expect(game.history()).toEqual(['f3', 'e5', 'g4'])
  expect(choice?.san).toBe('Qh4#')
})

test('clock expiry ends the game and prevents further moves', async ({ page }) => {
  await page.clock.install()
  await page.goto('/')
  await page.getByRole('button', { name: /Play a friend/ }).click()
  await page.getByRole('button', { name: 'e2 White pawn' }).click()
  await page.getByRole('button', { name: /e4 empty/ }).click()
  await page.clock.fastForward(301000)
  await expect(page.getByRole('status')).toContainText('White wins on time')
  await page.getByRole('button', { name: 'e7 Black pawn' }).click()
  await page.getByRole('button', { name: 'e5 empty' }).click()
  await expect(page.getByRole('button', { name: 'e7 Black pawn' })).toBeVisible()
})
